apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.appSecrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
