namespace: todoapp

image:
  repository: your-dockerhub-user/todoapp
  tag: "3.0.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

nodeAffinity:
  key: app
  value: todolist

secrets:
  appSecrets:
    SECRET_KEY: "supersecretkey123"
    OTHER_KEY: "value456"

serviceAccount:
  name: todoapp-sa
