namespace: todoapp

image:
  repository: ikulyk404/todoapp
  tag: "4.0.1"

resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "256Mi"
    cpu: "150m"

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

nodeAffinity:
  key: "app"
  value: "todoapp"

tolerations:
  - key: "app"
    operator: "Equal"
    value: "todoapp"
    effect: "NoSchedule"

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpu: 80
  memory: 80

secrets:
  SECRET_KEY: your_key
  DB_NAME: your_db
  DB_USER: your_user
  DB_PASSWORD: your_pass
  DB_HOST: your_host

serviceAccount:
  name: todoapp-reader
